google_project_id       = "peppy-house-314119"
google_bucket_name      = "zhanara11"
deployment_environment  = "dev"
deployment_name         = "hello-world"
credentials             = "fuchicorp-service-account.json" 
